<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYuzLWHS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYuzLWHS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYuzLWHS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYuzLWHS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYuzLWHS\App_KernelDevDebugContainer([
    'container.build_hash' => 'YuzLWHS',
    'container.build_id' => '47101d16',
    'container.build_time' => 1645604608,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYuzLWHS');
