<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9Bc5Yrd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9Bc5Yrd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9Bc5Yrd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9Bc5Yrd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9Bc5Yrd\App_KernelDevDebugContainer([
    'container.build_hash' => '9Bc5Yrd',
    'container.build_id' => '3bc55b8d',
    'container.build_time' => 1645456858,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9Bc5Yrd');
