<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXHxqhLx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXHxqhLx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXHxqhLx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXHxqhLx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXHxqhLx\App_KernelDevDebugContainer([
    'container.build_hash' => 'XHxqhLx',
    'container.build_id' => '21954f99',
    'container.build_time' => 1645603089,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXHxqhLx');
